export const PARTNERS = [
	// 'images/gorilla.png',
	// 'images/madyar.png',
	// 'images/nebo.png',
	// 'images/ugli.png',
	// 'images/villa-verde.png',
	// 'images/petrovich.png',
	// 'images/stariy-gorod.png',
	// 'images/team.png',
	// 'images/edim-doma.png',
	// 'images/vip-res.png',
	// 'images/the-pech.png',
	// 'images/co-co.png',
	// 'images/shan.png',
	'images/sen-soy.png',
	// 'images/gustav.png',
	'images/food-tech.png',
	'images/boridor.png',
];
